services:
  build:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: realtime-standalone
    ports:
      - '${APP_PORT:-3000}:3000' # choose a different host port if needed
    restart: unless-stopped
